# Generated by Django 4.0.4 on 2022-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='citablereference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='scopeContent_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
