# Generated by Django 4.0.4 on 2022-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna_app', '0003_rename_citablereference_record_citablereference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='message_to_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
